/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsIdSlugRouteImport } from './routes/products/$id.$slug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdSlugRoute = ProductsIdSlugRouteImport.update({
  id: '/products/$id/$slug',
  path: '/products/$id/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/products/$id/$slug': typeof ProductsIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/products/$id/$slug': typeof ProductsIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/products/$id/$slug': typeof ProductsIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products' | '/api/trpc/$' | '/products/$id/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/api/trpc/$' | '/products/$id/$slug'
  id: '__root__' | '/' | '/products/' | '/api/trpc/$' | '/products/$id/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ProductsIdSlugRoute: typeof ProductsIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id/$slug': {
      id: '/products/$id/$slug'
      path: '/products/$id/$slug'
      fullPath: '/products/$id/$slug'
      preLoaderRoute: typeof ProductsIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ProductsIdSlugRoute: ProductsIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
