/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoftwareIndexRouteImport } from './routes/software/index'
import { Route as ArtIndexRouteImport } from './routes/art/index'
import { Route as SoftwareIdSlugRouteImport } from './routes/software/$id.$slug'
import { Route as ArtIdSlugRouteImport } from './routes/art/$id.$slug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIndexRoute = ArtIndexRouteImport.update({
  id: '/art/',
  path: '/art/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIdSlugRoute = SoftwareIdSlugRouteImport.update({
  id: '/software/$id/$slug',
  path: '/software/$id/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIdSlugRoute = ArtIdSlugRouteImport.update({
  id: '/art/$id/$slug',
  path: '/art/$id/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/art': typeof ArtIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/art/$id/$slug': typeof ArtIdSlugRoute
  '/software/$id/$slug': typeof SoftwareIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/art': typeof ArtIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/art/$id/$slug': typeof ArtIdSlugRoute
  '/software/$id/$slug': typeof SoftwareIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/art/': typeof ArtIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/art/$id/$slug': typeof ArtIdSlugRoute
  '/software/$id/$slug': typeof SoftwareIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/art'
    | '/software'
    | '/api/trpc/$'
    | '/art/$id/$slug'
    | '/software/$id/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/art'
    | '/software'
    | '/api/trpc/$'
    | '/art/$id/$slug'
    | '/software/$id/$slug'
  id:
    | '__root__'
    | '/'
    | '/art/'
    | '/software/'
    | '/api/trpc/$'
    | '/art/$id/$slug'
    | '/software/$id/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtIndexRoute: typeof ArtIndexRoute
  SoftwareIndexRoute: typeof SoftwareIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ArtIdSlugRoute: typeof ArtIdSlugRoute
  SoftwareIdSlugRoute: typeof SoftwareIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/': {
      id: '/art/'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/$id/$slug': {
      id: '/software/$id/$slug'
      path: '/software/$id/$slug'
      fullPath: '/software/$id/$slug'
      preLoaderRoute: typeof SoftwareIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/$id/$slug': {
      id: '/art/$id/$slug'
      path: '/art/$id/$slug'
      fullPath: '/art/$id/$slug'
      preLoaderRoute: typeof ArtIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtIndexRoute: ArtIndexRoute,
  SoftwareIndexRoute: SoftwareIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ArtIdSlugRoute: ArtIdSlugRoute,
  SoftwareIdSlugRoute: SoftwareIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
